### ISSUE TITLE
Practica2 de Visual Studio

### ISSUE THREAD

**Issue by Nancy-0714** [SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-companion-ai#1]
[Mockup de interfaz grafica.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-companion-ai/files/14314878/Mockup.de.interfaz.grafica.pdf)

Integrantes:
Vanessa Cruz Ortiz.
Evelyn Santiago Victoria.
Nancy Olivera Santiago.

**Comment by Daniel-Velasco-Lopez** [comment]
Con respecto a la rúbrica, han obtenido un total de 82 punto de 100, ya que su conclusión únicamente cuenta con 5 líneas.

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
